server:
  port: 9999
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
#    driver-class-name: com.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
check-user-scopes: true
